# [shell]
#     program = "/usr/bin/zsh"
# args = ["-l"]

[window]
padding = {x = 20, y = 20}

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "regular" }
size = 12

[colors.primary]
background = "#111111"
foreground = "#efebec"

[colors.normal]
black = "#111111"
blue = "#FFFF00"
cyan = "#ffffff"
green = "#fdeb37"
magenta = "#475754"
red = "#c01e10"
white = "#cccccc"
yellow = "#FFFF00"

[cursor]
style = { shape = "Beam", blinking = "On"}

[keyboard]
bindings = [
    {key= "Return", mods= "Control", action= "SpawnNewInstance"},
]


